lib/genialais_web/router.ex
defmodule GenialaisWeb.Router do
  use GenialaisWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router,
    extensions: [PowInvitation]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GenialaisWeb.Plugs.Locale, "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :admin do
    plug GenialaisWeb.Plugs.EnsureRole, :admin
  end

  scope "/", GenialaisWeb do
    pipe_through [:browser]

    get "/", PageController, :index
  end

  scope "/", Pow.Phoenix, as: "pow" do
    pipe_through [:browser, :protected]
    
    resources "/registration", RegistrationController, singleton: true, only: [:edit, :update, :delete]
  end

  scope "/", PowInvitation.Phoenix, as: "pow_invitation" do
    pipe_through [:browser, :protected, :admin]

    resources "/invitations", InvitationController, only: [:new, :create, :show]
  end

  scope "/" do
    pipe_through :browser

    pow_session_routes()
    pow_extension_routes()
  end

  scope "/admin", GenialaisWeb do
    pipe_through [:browser, :protected, :admin]

    get "/", AdminController, :index
    post "/", AdminController, :update
    delete "/:uid", AdminController, :delete
  end

  scope "/user", GenialaisWeb do
    pipe_through [:browser, :protected]

    post "/", UserController, :update
  end

  scope "/individuals", GenialaisWeb do
    pipe_through [:browser, :protected]

    get "/", IndividualController, :index
    get "/new", IndividualController, :new
    get "/:id", IndividualController, :show
    post "/search", IndividualController, :search
    post "/create", IndividualController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", GenialaisWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: GenialaisWeb.Telemetry
    end
  end
end

lib/genialais_web/views/layout_view.ex
defmodule GenialaisWeb.LayoutView do
  use GenialaisWeb, :view

  def page_title(conn, assigns) do
    try do
      base_name = default_page_title()
      page = apply(view_module(conn), :page_title, [action_name(conn), assigns])
      "#{base_name} - #{page}"
    rescue
      UndefinedFunctionError -> default_page_title(conn, assigns)
    end
  end

  def default_page_title(), do: "Genialais"
  def default_page_title(_conn, _assigns), do: default_page_title()

  def languages do
    [
      "🇬🇧": "en", 
      "🇫🇷": "fr"
    ]
  end

  def active_class(conn, path) do
    [_head | [base_path | _tail]] = String.split(path, "/")

    conn.path_info
    |> List.first("")
    |> String.equivalent?(base_path)
    |> case do
      true -> "active"
      false -> nil
    end
  end

  def active_link(conn, text, opts) do
    class = [opts[:class], active_class(conn, opts[:to])]
            |> Enum.filter(& &1) 
            |> Enum.join(" ")
    opts = opts
          |> Keyword.put(:class, class)
    link(text, opts)
  end
end

lib/genialais_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Genialais · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="stylesheet" href="/assets/fontawsome-free/css/all.css" >
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Tangerine&display=swap"> 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= if Pow.Plug.current_user(@conn) do %>
            <%= form_for @conn, Routes.user_path(@conn, :update, %{}), fn f -> %>
              <%= select f, :locale, languages(), selected: Pow.Plug.current_user(@conn).locale, class: "locale-select", onchange: "this.form.submit()" %>
              <%= hidden_input f, :redirect_to, value: @conn.request_path %>
            <% end %>
            <%= link gettext("Sign out"), to: Routes.pow_session_path(@conn, :delete), method: :delete %>
          <% else %>
            <%= link "Sign in", to: Routes.pow_session_path(@conn, :new) %>
          <% end %>
        </nav>
        <a href="/">
          <span class="app-title">Genialais</span>
        </a>
      </section>
    </header>
    <div class="content-wrapper">
      <%= if Pow.Plug.current_user(@conn) do %>
      <div class="sidebar">
        <ul>
          <li>
            <%= link gettext("Home"), to: Routes.page_path(@conn, :index), class: active_class(@conn, Routes.page_path(@conn, :index)) %>
          </li>
          <li>
            <%= link gettext("Admin"), to: Routes.admin_path(@conn, :index), class: active_class(@conn, Routes.admin_path(@conn, :index)) %>
          </li>
        </ul>
      </div>
      <% end %>
      <main role="main" class="container">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= @inner_content %>
      </main>
    </div>
  </body>
</html>

lib/genialais_web/templates/layout/app.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= page_title(@conn, assigns) %></title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Tangerine&display=swap"> 
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= if Pow.Plug.current_user(@conn) do %>
            <%= form_for @conn, Routes.user_path(@conn, :update, %{}), fn f -> %>
              <%= select f, :locale, languages(), selected: Pow.Plug.current_user(@conn).locale, class: "locale-select", onchange: "this.form.submit()" %>
              <%= hidden_input f, :redirect_to, value: @conn.request_path %>
            <% end %>
            <%= link gettext("Sign out"), to: Routes.pow_session_path(@conn, :delete), method: :delete %>
          <% else %>
            <%= link "Sign in", to: Routes.pow_session_path(@conn, :new) %>
          <% end %>
        </nav>
        <a href="/">
          <span class="app-title">Genialais</span>
        </a>
      </section>
    </header>
    <div class="content-wrapper">
      <%= if Pow.Plug.current_user(@conn) do %>
      <div class="sidebar">
        <ul>
          <li class={active_class(@conn, Routes.page_path(@conn, :index))}>
            <a href={Routes.page_path(@conn, :index)}>
              <FontAwesome.LiveView.icon name="house" />
              <div><%=gettext "Home" %></div>
            </a>
          </li>
          <li class={active_class(@conn, Routes.individual_path(@conn, :index))}>
            <a href={Routes.individual_path(@conn, :index)}>
              <FontAwesome.LiveView.icon name="users" />
              <div><%=gettext "People" %></div>
            </a>
          </li>
          <li class={active_class(@conn, Routes.admin_path(@conn, :index))}>
            <a href={Routes.admin_path(@conn, :index)}>
              <FontAwesome.LiveView.icon name="gears" />
              <div><%=gettext "Admin" %></div>
            </a>
          </li>
        </ul>
      </div>
      <% end %>
      <main role="main" class="container">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= @inner_content %>
      </main>
    </div>
  </body>
</html>